### PR TITLE
Remove importable package warnings during `python -m build`, use conda.txt instead of pip.txt

### PR DESCRIPTION
**Pull request by bobleesj**
Closes https://github.com/diffpy/diffpy.pdfgui/issues/219

### CODE REVIEW

**Comment by bobleesj** [comment]
@sbillinge  ready for review - CI will fail since the run.txt has been removed. Once https://github.com/Billingegroup/release-scripts/pull/58 is merged and its `v0` is merged from `main`. The CI will most likely pass.

**Comment by sbillinge** [comment]
rerunning CI test after merging the new release-scripts worfklow PR into v0

**Comment by sbillinge** [comment]
merging, all tests pass now.

**Comment by bobleesj** [comment]
great!

**Pull request merged**
