### PR TITLE
Errordialog

### PR DESCRIPTION
**Pull request by dragonyanglong**
This PR is for issue #24 . It includes the following edits in the following, which are committed one by one. I feel like the current commits looks clear. I can merge some commits into one or split one commit into multiple if needed. `errorreportdialog.py` is sync with `design/errorreportdialog.wxg`

update `errorreportdialog` with recent glade version
drop error report form and `send report button`
add `Copy Error Log` and `Google This Error` buttons and their event handler codes
update the gui design, replacing all header text labels with one `wx.html.HtmlWindow`.

### CODE REVIEW

**Comment by pavoljuhas** [comment]
@dragonyanglong - I have finally got some time to check this PR and do a few fixups.
Could you please check if this looks OK to you?

A few small comments regarding the commit style:
- please wrap the commit body (2nd and later paragraphs) at 72 characters rather than using a single very long line (http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)
- make sure commit prefixes (MAINT, DEV, BUG, etc.) correspond to what is listed at https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message.  DEV is for "development tool or utility" and not for *development".  I used it for 0493f93d30b83fe094209f9d92f72aed23eee52e because that commit only concerned the travis test system and not project code.

**Comment by dragonyanglong** [comment]
Hi @pavoljuhas , I looked through your commits, and they look great to me. Thanks for correcting and updating the codes for me.  

I also rewrote my commit messages as you suggested. Are they look good to you? If not, please let me know, and I can change them accordingly. (I am not quite sure the difference btw `MAINT` and `ENH`)  I used `git rebase -i HEAD~10`, and only changing my commit messages, but it seems like your last four commits are also updated on github website (although nothing changed in your commits, and git log looks all good). 

Thanks a lot, Pavol!

**Comment by dragonyanglong** [comment]
BTW, the `codecov/patch` check looks failed, is that ok?

**Comment by dragonyanglong** [comment]
BTW, the `codecov/patch` check looks failed, is that ok?

**Comment by dragonyanglong** [comment]
BTW, the `codecov/patch` check looks failed, is that ok?

**Comment by pavoljuhas** [comment]
@dragonyanglong - thank you for checking and for improving commit messages.  I actually meant that comment for future work, but if you already fixed the commits here it's great.

> (I am not quite sure the difference btw MAINT and ENH)

To my understanding *MAINT* improves the existing code by fixing typos or refactoring (simplifying) the implementation (e.g., replacing hard-coded values with a module constant), but does not change what the affected functions do.  *ENH* adds some new functionality or features that did not exist before.

> BTW, the codecov/patch check looks failed, is that ok?

In this case yes.  The unit tests in PDFgui cover only its control layer, but not the GUI elements.

**Comment by pavoljuhas** [comment]
No worries it is not a big deal.  Thank you for fixing the error dialog!

**Pull request merged**
