### PR TITLE
black edits

### PR DESCRIPTION
**Pull request by cadenmyers13**
Screenshot 2024-07-16 at 12 41 10 PM

### CODE REVIEW

**Comment by cadenmyers13** [comment]
@sbillinge Can we merge this?

**Comment by sbillinge** [comment]
thanks @cadenmyers13 

Next, please copy the .flake8 and `black` configs (this latter is in `pyproject.toml`, but don't copy over the whole thing, just the [tool.black] part.  create a file with just this in if it is not there) and the `pre-commit-config.yaml` and start working on the flake8 fixes.   Please split them into a few PRs so I am reviewing 4 or 5 files at a time.  Periodically run the tests to make sure we didn't break anything!

Thanks so much.

**Comment by cadenmyers13** [comment]
@sbillinge Do you want me to create a `pyproject.toml` file with just the `[tool.black]` section in it? If so, should i remove `setup.py`?

**Comment by sbillinge** [comment]
> @sbillinge Do you want me to create a `pyproject.toml` file with just the `[tool.black]` section in it? If so, should i remove `setup.py`?

Good question.  Not yet.  If there is currently no pyproject.toml file, just create one and paste into it the `[tool.black]` section but nothing else.

**Comment by cadenmyers13** [comment]
> > @sbillinge Do you want me to create a `pyproject.toml` file with just the `[tool.black]` section in it? If so, should i remove `setup.py`?
> 
> Good question. Not yet. If there is currently no pyproject.toml file, just create one and paste into it the `[tool.black]` section but nothing else.

Got it. I already made the first PR with flake8 edits. I copied over the `.flake8` file in that PR so the sooner we can get that merged the more I can split up the edits into different PRs, unless there is a better way to do this?

**Comment by sbillinge** [comment]
> > > @sbillinge Do you want me to create a `pyproject.toml` file with just the `[tool.black]` section in it? If so, should i remove `setup.py`?
> > 
> > 
> > Good question. Not yet. If there is currently no pyproject.toml file, just create one and paste into it the `[tool.black]` section but nothing else.
> 
> Got it. I already made the first PR with flake8 edits. I copied over the `.flake8` file in that PR so the sooner we can get that merged the more I can split up the edits into different PRs, unless there is a better way to do this?

I will try and merge it, but the quickest way to get it merged is to put in a PR with just the flake8 file....

**Pull request merged**
