### PR TITLE
Files in doc directory

### PR DESCRIPTION
**Pull request by cadenmyers13**

### CODE REVIEW

**Comment by cadenmyers13** [comment]
@sbillinge Discussed a bit with Andrew on where we should put things and this is what I've got right now.

**Comment by cadenmyers13** [comment]
> this looks about right. Please make a PR with any changes that allow you to build the docs locally, and on a separate PR a workflow with the doc builds in a GitHub action, and we can work to make that pass too.

`docs.yml` is already added, no?

**Comment by sbillinge** [comment]
> > this looks about right. Please make a PR with any changes that allow you to build the docs locally, and on a separate PR a workflow with the doc builds in a GitHub action, and we can work to make that pass too.
> 
> `docs.yml` is already added, no?

Ah, ok.  Let me know when you are confident the docs are building locally and I can merge and it will test the docs build then

**Comment by cadenmyers13** [comment]
> > > this looks about right. Please make a PR with any changes that allow you to build the docs locally, and on a separate PR a workflow with the doc builds in a GitHub action, and we can work to make that pass too.
> > 
> > 
> > `docs.yml` is already added, no?
> 
> Ah, ok. Let me know when you are confident the docs are building locally and I can merge and it will test the docs build then

The htmls build when i run `make html` in `doc`. However im getting this error: 
Screenshot 2024-08-08 at 4 12 13 PM

**Comment by sbillinge** [comment]
I merged this so we will need the fixes for this on a new PR.  Thanks.

**Pull request merged**
